### ISSUE TITLE
Provide a prop to assign a class name to the main container

### ISSUE THREAD

**Issue by Charith47** [ejirocodes/vue3-otp-input#29]
I want to apply styles to main container of input divs shown below. Currently there is no way to provide a class name to the main div. Can only style each individual inputs.

![image](https://user-images.githubusercontent.com/61795948/209785831-b51f6f10-d974-4c38-97cd-e49cc4430325.png)

A prop to provide a class name for the main container would solve this problem.

For now, I'm using an attribute name to target the main container (works for my specific scenario).

```css
div[is-input-num='true'] {
    justify-content: space-between;
}
```
